# Generated by Django 2.2.9 on 2020-03-01 12:49

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_color',
            field=colorful.fields.RGBColorField(default='#373a3c'),
        ),
        migrations.AlterField(
            model_name='technologiespage',
            name='title_color',
            field=colorful.fields.RGBColorField(default='#373a3c'),
        ),
    ]
