# Generated by Django 2.2.9 on 2020-03-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_color',
            field=models.CharField(default='#373a3c', max_length=10),
        ),
        migrations.AlterField(
            model_name='technologiespage',
            name='title_color',
            field=models.CharField(default='#373a3c', max_length=10),
        ),
    ]
