# Generated by Django 2.2.12 on 2020-05-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200301_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='title_color',
        ),
        migrations.RemoveField(
            model_name='technologiespage',
            name='title_color',
        ),
    ]
