# Generated by Django 2.0.7 on 2018-07-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_portfoliopage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='summary',
            field=models.CharField(help_text='Short description to show on tiles and lists', max_length=511),
        ),
    ]
