# Generated by Django 2.0.7 on 2018-07-27 12:48

from django.db import migrations


def create_taginfos(apps, schema_editor):
    Tag = apps.get_model('taggit', 'Tag')
    TechnologyInfo = apps.get_model('home', 'TechnologyInfo')
    for tag in Tag.objects.all():
        TechnologyInfo.objects.get_or_create(tag=tag)


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0010_auto_20180727_1247'),
        ('taggit', '0002_auto_20150616_2121')
    ]

    operations = [
        migrations.RunPython(create_taginfos),
    ]
