# Generated by Django 2.0.7 on 2018-07-27 13:18

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180727_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technologyinfo',
            options={'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
        migrations.AlterField(
            model_name='technologyinfo',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
