# Generated by Django 2.0.7 on 2018-08-01 13:39

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20180727_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
    ]
