# Generated by Django 2.0.8 on 2018-08-01 18:13

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_title_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologiespage',
            name='title_color',
            field=colorful.fields.RGBColorField(default='#FFFFFF'),
        ),
    ]
