# Generated by Django 2.0.9 on 2018-10-10 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_projectpage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'ordering': ('-start_date',)},
        ),
    ]
