# Generated by Django 2.0.9 on 2018-10-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181010_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
