# Generated by Django 2.0.9 on 2018-10-16 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0019_auto_20181011_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='card_background',
            field=models.ForeignKey(blank=True, help_text='Card background on the portfolio view', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
