# Generated by Django 2.0.9 on 2018-10-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_projectpage_card_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='claim',
            field=models.CharField(default='Freelance python developer', help_text='Claim text placed under the name', max_length=300),
        ),
    ]
