# Generated by Django 2.0.9 on 2018-10-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('home', '0021_homepage_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='My picture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
