# Generated by Django 2.0.9 on 2018-10-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0007_merge'),
        ('home', '0025_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='reference_letter',
            field=models.ForeignKey(blank=True, help_text='Reference letter for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
