# Generated by Django 2.0.9 on 2018-10-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20181021_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='earliest_available',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
