# Generated by Django 2.0.9 on 2018-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20181021_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='responsibility',
            field=models.CharField(default='Backend developer', max_length=100),
        ),
    ]
