# Generated by Django 2.0.9 on 2018-12-08 16:50

from django.db import migrations
import bleach


def bleach_responsibility(apps, schema_editor):
    ProjectPage = apps.get_model('home', 'ProjectPage')
    for project_page in ProjectPage.objects.all():
        project_page.responsibility = bleach.clean(project_page.responsibility, strip=True)
        project_page.save()


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0030_auto_20181208_1648'),
    ]

    operations = [
        migrations.RunPython(bleach_responsibility),
    ]
