# Generated by Django 2.0.9 on 2018-12-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20181208_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='responsibility',
            new_name='position',
        ),
    ]
