# Generated by Django 2.0.9 on 2018-12-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0033_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='responsibilities',
            field=models.ManyToManyField(related_name='projects', to='home.Responsibility'),
        ),
    ]
