# Generated by Django 2.0.9 on 2018-12-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_projectpage_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyinfo',
            name='match_in_cv',
            field=models.BooleanField(default=True, help_text='Match for technology in CV relevant projects?'),
        ),
    ]
