# Generated by Django 2.0.9 on 2018-12-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_technologyinfo_match_in_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
