# Generated by Django 2.0.9 on 2018-12-27 19:33

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20181210_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='responsibilities',
            field=modelcluster.fields.ParentalManyToManyField(related_name='projects', to='home.Responsibility'),
        ),
    ]
