# Generated by Django 2.0.9 on 2019-01-15 14:59

from django.db import migrations


def copy_tags(apps, schema_editor):
    Tag = apps.get_model('taggit', 'Tag')
    for tag in Tag.objects.all():
        project_technologies = tag.home_projecttechnology_items.all()
        if project_technologies:
            for project_technology in project_technologies:
                project = project_technology.content_object
                project.technologies_temp.add(tag.info)
                project.technologies_temp.all()


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0039_projectpage_technologies_temp'),
        ('taggit', '0001_initial'),

    ]

    operations = [
        migrations.RunPython(copy_tags),
    ]
