# Generated by Django 2.0.9 on 2019-01-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190115_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyinfo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
