# Generated by Django 2.0.9 on 2019-01-15 15:50

from django.db import migrations


def copy_tag_names(apps, schema_editor):
    TechnologyInfo = apps.get_model('home', 'TechnologyInfo')
    for technology in TechnologyInfo.objects.all():
        technology.name = technology.tag.name
        technology.save()


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0041_technologyinfo_name'),
    ]

    operations = [
        migrations.RunPython(copy_tag_names),

    ]
