# Generated by Django 2.0.9 on 2019-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20190115_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologyinfo',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
