# Generated by Django 2.0.9 on 2019-01-15 15:59

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0043_auto_20190115_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='technologies_temp',
            field=modelcluster.fields.ParentalManyToManyField(related_name='projects', to='home.TechnologyInfo'),
        ),
    ]
