# Generated by Django 2.0.9 on 2019-01-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_migrate_cv_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyinfo',
            name='tag',
        ),
    ]
