# Generated by Django 2.0.9 on 2019-01-15 17:02

from django.db import migrations


def remove_tags(apps, schema_editor):
    Tag = apps.get_model('taggit', 'Tag')
    TechnologyInfo = apps.get_model('home', 'TechnologyInfo')

    for tag in Tag.objects.all():
        if TechnologyInfo.objects.filter(name=tag.name).exists():
            tag.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0001_initial'),
        ('home', '0046_remove_technologyinfo_tag')
    ]

    operations = [
        migrations.RunPython(remove_tags),

    ]
