# Generated by Django 2.0.9 on 2019-01-15 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_remove_projectpage_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectpage',
            old_name='technologies_temp',
            new_name='technologies',
        ),
    ]
