# Generated by Django 2.0.9 on 2019-01-15 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20190115_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttechnology',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='projecttechnology',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ProjectTechnology',
        ),
    ]
