# Generated by Django 2.0.9 on 2019-01-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('crm', '0034_remove_cv_relevant_skills'),
        ('home', '0050_auto_20190115_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnologyInfo',
            new_name='Technology',
        ),
    ]
