# Generated by Django 2.0.9 on 2019-01-15 18:48

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0051_auto_20190115_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='responsibilities',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects',
                                                              to='home.Responsibility'),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='technologies',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='projects',
                                                              to='home.Technology'),
        ),
    ]
