# Generated by Django 2.2.1 on 2019-06-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_contactpage_show_on_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='card_background',
        ),
    ]
