# Generated by Django 2.0.9 on 2018-11-07 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='Lead channel this company came from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Channel'),
        ),
    ]
