# Generated by Django 2.2.12 on 2020-05-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20191206_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'city'},
        ),
    ]
