# Generated by Django 2.0.9 on 2018-11-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20181107_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='default_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=6, null=True),
        ),
    ]
