# Generated by Django 2.0.9 on 2018-11-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20181107_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='default_daily_rate',
            new_name='daily_rate',
        ),
    ]
