# Generated by Django 2.0.9 on 2018-11-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20181108_0956'),
    ]
    atomic = False
    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Recruiter'
        ),
        migrations.RenameField(
            model_name='project',
            old_name='company',
            new_name='recruiter',
        ),
    ]
