# Generated by Django 2.0.9 on 2018-11-08 10:05

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181108_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Lead channel this company came from', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.Channel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.ClientCompany'),
        ),
    ]
