# Generated by Django 2.0.9 on 2018-11-08 10:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20181108_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=django_fsm.FSMField(default='requested', max_length=50),
        ),
    ]
