# Generated by Django 2.0.9 on 2018-11-08 14:09

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20181108_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
    ]
