# Generated by Django 2.2.16 on 2020-09-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_cv_project_listing_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='projectmessage',
            options={'get_latest_by': 'modified'},
        ),
    ]
