# Generated by Django 3.2.4 on 2021-06-30 12:53

from django.db import migrations


def set_all_empty_projects(apps, schema_editor):
    Project = apps.get_model('crm.Project')
    for project in Project.objects.all():
        if not project.name:
            print(project.pk)
            project.name = "EMPTY"
            project.save()


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0011_auto_20200908_1347'),
    ]

    operations = [
        migrations.RunPython(set_all_empty_projects),
    ]
