# Generated by Django 2.0.9 on 2018-11-08 18:51

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_project_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcompany',
            options={'verbose_name_plural': 'clients'},
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='is_hr',
        ),
        migrations.AddField(
            model_name='clientcompany',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
        ),
    ]
