# Generated by Django 2.0.9 on 2018-11-08 18:52

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20181108_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, default=''),
        ),
    ]
