# Generated by Django 2.0.9 on 2018-11-08 19:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20181108_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcompany',
            options={'verbose_name': 'client', 'verbose_name_plural': 'clients'},
        ),
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name_plural': 'recruiters'},
        ),
        migrations.AddField(
            model_name='project',
            name='original_description',
            field=wagtail.core.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
