# Generated by Django 2.0.9 on 2018-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20181108_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
