# Generated by Django 2.0.9 on 2018-11-09 13:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_project_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
