# Generated by Django 2.0.9 on 2018-11-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_employee_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in months', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
