# Generated by Django 2.0.9 on 2018-11-10 15:57

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20181110_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
