# Generated by Django 2.0.9 on 2018-11-15 16:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20181115_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmessage',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='messages',
            field=models.ManyToManyField(editable=False, related_name='authors', through='crm.ProjectMessage', to='django_mailbox.Message'),
        ),
        migrations.AlterField(
            model_name='project',
            name='messages',
            field=models.ManyToManyField(editable=False, related_name='projects', through='crm.ProjectMessage', to='django_mailbox.Message'),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_messages', to='django_mailbox.Message'),
        ),
    ]
