# Generated by Django 3.2.5 on 2021-07-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='attach_cv',
            field=models.BooleanField(default=True, help_text='Attach CV by default for this template'),
        ),
    ]
