# Generated by Django 3.2.5 on 2021-07-29 09:28

import crm.models.message_templates
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_messagetemplate_attach_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='attach_cv',
            field=models.BooleanField(default=True, help_text='Attach CV by default for this template', verbose_name='Attach CV'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='text',
            field=wagtail.core.fields.RichTextField(help_text='Text of the message. Following context is available:{{project}} - project{{project.manager}} - manager{{project.company}} - company', validators=[crm.models.message_templates.valid_django_template]),
        ),
    ]
