# Generated by Django 2.0.9 on 2018-11-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_mailbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailbox',
            options={'verbose_name_plural': 'mailboxes'},
        ),
    ]
