# Generated by Django 3.2.5 on 2021-07-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20210729_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
