# Generated by Django 2.0.9 on 2018-11-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_auto_20181119_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='recruiter',
        ),
    ]
