# Generated by Django 3.2.5 on 2021-08-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_services'),
        ('crm', '0025_employee_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='hihlighted_project_pages',
            field=models.ManyToManyField(blank=True, help_text='Project pages placed first and visually highlighted for this CV and project lead', related_name='applications_highlighted_pages', to='home.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='relevant_project_pages',
            field=models.ManyToManyField(blank=True, help_text='Project pages to be placed on the first page, eye catcher for this project', related_name='applications_relevant_pages', to='home.ProjectPage'),
        ),
    ]
