# Generated by Django 3.2.5 on 2021-08-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_auto_20210803_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='hihlighted_project_pages',
            new_name='highlighted_project_pages',
        ),
    ]
