# Generated by Django 3.2.5 on 2021-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_rename_hihlighted_project_pages_cv_highlighted_project_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=10),
        ),
    ]
