# Generated by Django 2.0.9 on 2018-12-06 20:32

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_auto_20181206_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='working_permit',
            field=wagtailmarkdown.fields.MarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvgenerationsettings',
            name='default_working_permit',
            field=wagtailmarkdown.fields.MarkdownField(default='PERMANENT RESIDENCE'),
        ),
    ]
