# Generated by Django 3.2.5 on 2021-08-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_auto_20210804_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='message_id',
            field=models.CharField(default='MIGRATED', help_text='Message-id header of the original message', max_length=300),
            preserve_default=False,
        ),
    ]
