# Generated by Django 2.0.9 on 2018-12-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0029_auto_20181206_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'CV'},
        ),
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='Picture to use, default is the one used on home page',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.Image'),
        ),
    ]
