# Generated by Django 3.2.5 on 2021-08-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_projectmessage_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='reply_to',
            field=models.EmailField(default='MIGRATED', help_text='Reply-to header of the original message', max_length=254),
            preserve_default=False,
        ),
    ]
