# Generated by Django 2.0.9 on 2018-12-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_auto_20181207_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='skills',
            new_name='relevant_skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='project_pages',
        ),
    ]
