# Generated by Django 2.0.9 on 2018-12-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0031_auto_20181207_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='relevant_project_pages',
            field=models.ManyToManyField(
                blank=True,
                help_text='Project pages to be placed on the first page, eye catcher for this project',
                related_name='applications_highlighted', to='home.ProjectPage'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='relevant_skills',
            field=models.ManyToManyField(
                blank=True,
                help_text='Technology tags to be included, will be automatically formed to look relevant',
                to='taggit.Tag'),
        ),
    ]
