# Generated by Django 3.2.5 on 2021-08-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_alter_projectmessage_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
