# Generated by Django 2.0.9 on 2019-01-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_cv_relevant_skills_temp'),
        ('home', '0045_migrate_cv_skills')
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='relevant_skills',
        ),
    ]
