# Generated by Django 2.0.9 on 2019-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0033_cv_relevant_skills_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='relevant_skills_temp',
        ),
        migrations.AlterField(
            model_name='cv',
            name='relevant_skills',
            field=models.ManyToManyField(
                blank=True,
                help_text='Technologies to be included, will be automatically formed to look relevant',
                to='home.TechnologyInfo'),
        ),
    ]
