# Generated by Django 2.0.9 on 2019-01-17 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('crm', '0036_employee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
    ]
