# Generated by Django 2.0.9 on 2019-01-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0038_clientcompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='wagtailimages.Image'),
        ),
    ]
