# Generated by Django 2.0.9 on 2019-01-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0039_auto_20190117_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.City'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.City'),
        ),
    ]
