# Generated by Django 2.0.9 on 2019-01-24 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_auto_20190117_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='crm.Project'),
        ),
    ]
