# Generated by Django 2.0.9 on 2019-01-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('crm', '0041_auto_20190124_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvgenerationsettings',
            name='default_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
    ]
