# Generated by Django 2.0.9 on 2019-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_cvgenerationsettings_default_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
