# Generated by Django 2.0.9 on 2019-01-24 16:22

from django.db import migrations


def migration_project_names(apps, schema_editor):
    Project = apps.get_model('crm', 'Project')
    for project in Project.objects.filter(name=None):
        if project.company:
            project.name = str(project.company.name)
        elif project.manager:
            project.name = str(project.manager.company.name)
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0043_project_name'),
    ]

    operations = [
        migrations.RunPython(migration_project_names)
    ]
