# Generated by Django 2.0.9 on 2019-01-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_auto_20190124_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'city'},
        ),
    ]
