# Generated by Django 2.0.9 on 2019-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_auto_20190124_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created'], 'verbose_name_plural': 'people'},
        ),
    ]
