# Generated by Django 2.1.5 on 2019-01-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0046_auto_20190124_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mailbox',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='project',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='projectmessage',
            name='message',
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages',
                                    to='crm.Employee'),
        ),
        migrations.AlterField(
            model_name='projectmessage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='messages', to='crm.Project'),
        ),
    ]
