# Generated by Django 2.1.5 on 2019-01-26 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_auto_20190126_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='gmail_message_id',
            field=models.CharField(default='migrated', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='gmail_thread_id',
            field=models.CharField(default='migrated', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Sending time'),
        ),
    ]
