# Generated by Django 2.1.5 on 2019-01-28 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0048_auto_20190126_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projectmessage',
            name='text',
            field=models.TextField(default='migrated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='projects', to='crm.City'),
        ),
    ]
