# Generated by Django 2.1.5 on 2019-01-29 15:33

from django.db import migrations


def remove_old_messages(apps, schema_editor):
    ProjectMessage = apps.get_model('crm', 'ProjectMessage')
    ProjectMessage.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0049_auto_20190128_2154'),
    ]

    operations = [
        migrations.RunPython(remove_old_messages)
    ]
