# Generated by Django 2.1.5 on 2019-02-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0050_auto_20190129_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='picture',
            field=models.ForeignKey(blank=True, help_text='Picture to use', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to='wagtailimages.Image'),
        ),
    ]
