# Generated by Django 2.1.5 on 2019-02-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_auto_20190205_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='include_portfolio',
            field=models.BooleanField(default=True, help_text="Include portfolio projects' description"),
        ),
    ]
