# Generated by Django 2.1.5 on 2019-02-05 16:30

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_cv_include_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='rate_overview',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
