# Generated by Django 2.1.5 on 2019-02-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0053_auto_20190205_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='cvs', to='crm.Project'),
        ),
    ]
