# Generated by Django 2.1.5 on 2019-04-01 11:20

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import wagtail.contrib.table_block.blocks
import wagtail.core.fields
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0054_auto_20190205_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created',
                 django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified',
                 django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('language',
                 models.CharField(choices=[('en', 'English'), ('de', 'German')], default='en', max_length=4)),
                ('unit', models.CharField(default='hour', help_text='Work unit', max_length=200)),
                ('vat', models.FloatField(default=19, help_text='VAT in %')),
                ('invoice_number', models.CharField(max_length=20)),
                ('payment_period',
                 models.PositiveIntegerField(default=14, help_text='Amount of days for this invoice to be payed')),
                ('payment_address', wagtailmarkdown.fields.MarkdownField()),
                ('receiver_vat_id', models.CharField(help_text='VAT ID of the receiver (you)', max_length=100)),
                ('sender_vat_id', models.CharField(help_text='VAT ID of the sender (client)', max_length=100)),
                ('issued_date', models.DateField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('tax_id', models.CharField(help_text='Your local tax id', max_length=100)),
                ('bank_account', wagtailmarkdown.fields.MarkdownField(help_text='Payment bank account details')),
                ('contact_data', wagtailmarkdown.fields.MarkdownField()),
                ('title', wagtailmarkdown.fields.MarkdownField()),
                ('table', wagtail.core.fields.StreamField([('positions', wagtail.contrib.table_block.blocks.TableBlock(
                    table_options={'autoColumnSize': False, 'colHeaders': False, 'editor': 'text', 'height': 216,
                                   'language': 'en', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False,
                                   'startCols': 4, 'startRows': 6, 'stretchH': 'all'}))])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices',
                                              to='crm.Project')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
