# Generated by Django 2.1.8 on 2019-04-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('crm', '0057_auto_20190401_1443'), ('crm', '0058_auto_20190401_1444'), ('crm', '0059_auto_20190401_1452')]

    dependencies = [
        ('crm', '0056_auto_20190401_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issued_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='Python development', max_length=200),
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='table',
            new_name='positions',
        ),
    ]
