# Generated by Django 2.1.8 on 2019-04-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_remove_invoicegenerationsettings_default_payment_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicegenerationsettings',
            name='default_sender_vat_id',
        ),
    ]
