# Generated by Django 2.1.8 on 2019-04-29 13:22

from django.db import migrations


def copy_companies_to_recruiters(apps, schema_editor):
    ClientCompany = apps.get_model('crm', 'ClientCompany')
    Recruiter = apps.get_model('crm', 'Recruiter')

    for company in ClientCompany.objects.all():
        recruiter, created = Recruiter.objects.get_or_create(
            name=company.name,
            defaults={
                'location': company.location,
                'channel': company.channel,
                'url': company.url,
                'notes': company.notes,
                'logo': company.logo
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0059_remove_invoicegenerationsettings_default_sender_vat_id'),
    ]

    operations = [
        migrations.RunPython(copy_companies_to_recruiters)
    ]
