# Generated by Django 2.1.8 on 2019-04-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0060_auto_20190429_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.Recruiter'),
        ),
    ]
