# Generated by Django 2.1.8 on 2019-04-29 14:35

from django.db import migrations


def migrate_project_company(apps, schema_editor):
    Project = apps.get_model('crm', 'Project')
    Recruiter = apps.get_model('crm', 'Recruiter')

    for project in Project.objects.exclude(company=None):
        project.company_recruiter = Recruiter.objects.get(name=project.company.name)
        assert project.company_recruiter is not None


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0061_project_company_recruiter'),
    ]

    operations = [
        migrations.RunPython(migrate_project_company)
    ]
