# Generated by Django 2.1.8 on 2019-04-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_auto_20190429_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
    ]
