# Generated by Django 2.1.8 on 2019-04-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_remove_project_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='company_recruiter',
            new_name='company',
        ),
    ]
