# Generated by Django 2.1.8 on 2019-04-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_auto_20190429_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='clientcompany',
            name='location',
        ),
        migrations.RemoveField(
            model_name='clientcompany',
            name='logo',
        ),
        migrations.DeleteModel(
            name='ClientCompany',
        ),
    ]
