# Generated by Django 2.1.8 on 2019-04-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_auto_20190429_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiter',
            options={'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
    ]
