# Generated by Django 2.1.8 on 2019-04-29 15:45

from django.db import migrations
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_auto_20190429_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_address',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, null=True),
        ),
    ]
