# Generated by Django 2.1.8 on 2019-05-01 17:10

from django.db import migrations, models
import wagtailmarkdown.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_company_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat_id',
            field=models.CharField(blank=True, help_text='VAT ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_address',
            field=wagtailmarkdown.fields.MarkdownField(help_text='Copied from the company, if empty'),
        ),
    ]
