# Generated by Django 2.1.8 on 2019-05-01 17:28

from django.db import migrations, models
import wagtailmarkdown.fields


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0069_auto_20190501_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_address',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, help_text='Copied from the company, if empty'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sender_vat_id',
            field=models.CharField(blank=True,
                                   help_text='VAT ID of the sender (client), copied from the company if empty',
                                   max_length=100),
        ),
    ]
