# Generated by Django 2.1.8 on 2019-05-05 17:10

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0070_auto_20190501_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='positions',
            field=wagtail.core.fields.StreamField([('positions', wagtail.contrib.table_block.blocks.TableBlock(
                table_options={'autoColumnSize': False, 'colHeaders': ['Article', 'Amount units', 'Price per unit'],
                               'columns': [{'data': 'article'}, {'data': 'amount', 'type': 'numeric'},
                                           {'data': 'price', 'format': '0.00', 'type': 'numeric'}], 'editor': 'text',
                               'height': 216, 'language': 'en', 'minSpareRows': 0, 'renderer': 'text',
                               'rowHeaders': False, 'stretchH': 'all'}))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=19, help_text='VAT in %', max_digits=4),
        ),
    ]
