# Generated by Django 2.1.8 on 2019-05-05 19:44

from django.db import migrations, models
import wagtail.contrib.table_block.blocks
import wagtail.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0071_auto_20190505_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='positions',
            field=wagtail.core.fields.StreamField([('positions', wagtail.contrib.table_block.blocks.TableBlock(
                table_options={'autoColumnSize': False, 'colHeaders': ['Article', 'Amount units', 'Price per unit'],
                               'columns': [{'data': 'article'}, {'data': 'amount', 'type': 'numeric'},
                                           {'data': 'price', 'format': '0.00', 'type': 'numeric'}],
                               'contextMenu': False, 'editor': 'text', 'height': 216, 'language': 'en',
                               'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': False, 'stretchH': 'all'}))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unit',
            field=models.CharField(default='hours', help_text='Work unit', max_length=200),
        ),
    ]
