# Generated by Django 2.2.1 on 2019-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_auto_20190505_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
