# Generated by Django 2.2.1 on 2019-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_invoice_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('€', 'Euro'), ('$', 'USD')], default='€', max_length=4),
        ),
    ]
